trigger: ['master']
pr: none

pool:
  vmImage: 'ubuntu-20.04'
steps:

#Installing cordova
- bash: |
    sudo npm i -g cordova
  displayName: 'npm i -g cordova@latest'

# Building App Android
- bash: |
    npx ionic cordova build android --no-build --release
  displayName: 'ionic cordova build android --no-build --release'

# https://www.softprayog.in/troubleshooting/error-while-loading-shared-libraries-libz-so-1
- bash: |
    sudo apt-get install lib32z1
  displayName: 'sudo apt-get install lib32z1'

- task: CopyFiles@2
  displayName: 'copy **/outputs/apk/release/app*.apk to $(Build.BinariesDirectory)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/outputs/apk/release/app*.apk'
    CleanTargetFolder: true
    TargetFolder: '$(Build.BinariesDirectory)'
    flattenFolders: true
    

- publish: '$(Build.BinariesDirectory)'
  artifact: 'android-app'
  displayName: 'publish artifact'